version: '3'
services:
  web:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - elasticsearch
  elasticsearch:
    image: "elasticsearch:6.5.4"
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300



